### ISSUE TITLE
Uncaught (in promise) DOMException: The element has no supported sources. line 101 in index.html in audio-basics.

### ISSUE THREAD

**Issue by omnicoder9** [mdn/webaudio-examples#115]
### What information was incorrect, unhelpful, or incomplete?

The audio-basics example does not work .  Uncaught (in promise) DOMException: The element has no supported sources. line 101 in index.html in audio-basics.

### What did you expect to see?

I was expecting the example to work.

**Comment by caugner** [comment]
@omnicoder9 How did you try out the example? I looked at https://mdn.github.io/webaudio-examples/audio-basics/ in Firefox and the example seems to work.

**Comment by caugner** [comment]
Thanks again for raising this issue.

As we haven't heard back from you, we will go ahead and close this issue. If you think it's still relevant, please reply to the previous comment and reopen the issue. 🙏 

We appreciate your understanding.
