### ISSUE TITLE
[step-sequencer] The slider input to set the DTMF rate is not working as expected

### ISSUE THREAD

**Issue by ManuLintz** [mdn/webaudio-examples#118]
### What information was incorrect, unhelpful, or incomplete?

This input doesn't behave as it should:
![image](https://github.com/mdn/webaudio-examples/assets/23702487/e38f2867-ecc6-49e8-8a24-d6135413e817)

### What did you expect to see?

When setting the slider like this, we don't hear anything anymore ([here](https://mdn.github.io/webaudio-examples/step-sequencer/)):
<img width="839" alt="image" src="https://github.com/mdn/webaudio-examples/assets/23702487/8d453587-112e-46b0-863c-e41fbc522112">

The problem comes from that the value is cast into an int in the event listener callback (also happens in https://github.com/mdn/webaudio-examples/issues/117).
```javascript
rateControl.addEventListener(
  "input",
  (ev) => {
    playbackRate = parseInt(ev.target.value, 10);
  },
  false
);
```
It was written to have a 0.1 step:
```html
<section class="controls">
  <label for="rate">Rate</label>
  <input
    name="rate"
    id="rate"
    type="range"
    min="0.1"
    max="2"
    value="1"
    step="0.1"
  />
</section>
```

Since I identified what causes the issue in the code I'd be happy to work on a fix + updating the doc.

**Comment by bsmth** [comment]
Thanks a lot for reporting it! There's a PR open which should fix this

>Since I identified what causes the issue in the code I'd be happy to work on a fix + updating the doc.

Sorry I missed this, would you like to [update the doc](https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Advanced_techniques) after this is merged?

**Comment by ManuLintz** [comment]
Yes sure, I'd love to
