### ISSUE TITLE
AnalyserNode error: GET https://mdn.github.io/audio-analyser/viper.ogg 404

### ISSUE THREAD

**Issue by pjmartorell** [mdn/webaudio-examples#24]
There is an error in the demo of AnalyserNode (https://mdn.github.io/webaudio-examples/audio-analyser/). The played song located in https://mdn.github.io/audio-analyser/viper.ogg does not exist anymore.

**Comment by pjmartorell** [comment]
Hi, I think this has nothing to do with decoding or Github, it's simpler. I see the path to the OGG/MP3 file is not correct. The file is not found because it's trying to find it in `https://mdn.github.io/audio-analyser/viper.ogg` instead of `https://mdn.github.io/webaudio-examples/audio-analyser/viper.mp3`. Checking the source code I see that there is a parameter pointing to the audio:

`var audioUrl = "/audio-analyser/viper.mp3"`

This should be:

`var audioUrl = "/webaudio-examples/audio-analyser/viper.mp3"` 

Hope it helps :)

**Comment by chrisdavidmills** [comment]
Ha ha, now I feel silly ;-)

Thanks for helping me fix this. I've made a the change and it works now.

**Comment by pjmartorell** [comment]
hahah don't worry, this happens to me sometimes as well :see_no_evil:
