### ISSUE TITLE
Switch on/off button not implemented

### ISSUE THREAD

**Issue by pjmartorell** [mdn/webaudio-examples#25]
https://github.com/mdn/webaudio-examples/blob/e7f0c804b4bd3c49bcbb9eaf751943133df56da1/audio-basics/index.html#L33

**Comment by chrisdavidmills** [comment]
This is true. @Rumyra , was this intentional? I don't think it is a big deal in any case.

**Comment by Rumyra** [comment]
Yes this was intentional I was pre-empting phase two of the boombox.

I can happily remove the button and re-implement for version 2 if it's a problem/confusing?

**Comment by chrisdavidmills** [comment]
Yeah, I think commenting out for now would be good

**Comment by rohini-ranjanR** [comment]
Hi, @Rumyra If the issue is open can I temporarily delete it or comment button to contribute to it?
Thanks

**Comment by rohini-ranjanR** [comment]
Thanks, @Rumyra here's my PR.
