### ISSUE TITLE
what kind of audio format does decodeAudioData support?

### ISSUE THREAD

**Issue by woshishuxiong** [mdn/webaudio-examples#3]
In the demo, an ogg format file is used in the decodeAudioData interface. I try aac and aacplus audio data, but the demo do not work and the chrome ouputs error like "Unable to decode audio data".

**Comment by chrisdavidmills** [comment]
Yeah, you need to use an audio format that the browser understands. In the modern world, mp3 would be the best, as most browsers support this now (either natively, or by passing it to a program that does support it.)

You can find a list of formats the browser supports at 

https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats

It looks like AAC is only supported in Chrome when contained inside an MP4 container. Hrm.

**Comment by woshishuxiong** [comment]
Thanks for your response. I try to fill the aac raw into an adts container, and then the adts can be decoded successfully. I think MP4 container is also OK. ^_^
