### ISSUE TITLE
Some directories are missing in README.md

### ISSUE THREAD

**Issue by matt-eric** [mdn/webaudio-examples#39]
The  "multi-track",  "output-timestamp",  and  "spacialization" directories are missing from the README.md. I would like to write descriptions for these directories.

**Comment by chrisdavidmills** [comment]
@matt-eric that would be super-helpful, please do!

I've assigned you to this issue.

**Comment by matt-eric** [comment]
Awesome, @chrisdavidmills. Thanks!
