### ISSUE TITLE
Make headers in README.md consistent

### ISSUE THREAD

**Issue by matt-eric** [mdn/webaudio-examples#41]
I realized that the headers I added for the directory descriptions in https://github.com/mdn/webaudio-examples/pull/38 are not consistent.

(e.g. the header for the "audio-basics" directory is "Audio Basics" and the header for the "decode-audio-data" is "decodeAudioData"). I did this because some directory names are associated with a specific method, whereas others are more of a description. 

For consistency purposes, I think it makes sense for all headers to be capital letters separated by spaces. If there is a method name associated with the directory, then it will appear in the description.

Thoughts on this, @chrisdavidmills?

**Comment by chrisdavidmills** [comment]
@matt-eric sure, that makes sense to me. All I'd add is that MDN standard practice is for headings to use sentence case rather than all capitalized, so I'd prefer that.
