### ISSUE TITLE
Hyperlink methods and objects in directory descriptions to MDN Web Audio API docs

### ISSUE THREAD

**Issue by matt-development-work** [mdn/webaudio-examples#42]
Most of the directory descriptions reference at least one method or object from the Web Audio API (e.g. `AudioParam`, `createDynamicsCompressor()`, or `MediaRecorder`). I'd be happy to hyperlink all methods and objects to their respective URLs in the MDN Web Audio API docs. Some are already hyperlinked.

**Comment by chrisdavidmills** [comment]
Cool, thanks.

**Comment by yanzq-x** [comment]
> 太好了，谢谢。

Can I add a wechat

**Comment by teoli2003** [comment]
Looking at the README.md file, it seems to me that this has been solved. If I'm mistaken, feel free to reopen this issue, and/or create a PR. I would happily review it.

(Thanks a lot)
