### ISSUE TITLE
Multi track example could have mixing capabilities

### ISSUE THREAD

**Issue by mattfsourcecode** [mdn/webaudio-examples#45]
The [Multi track](https://mdn.github.io/webaudio-examples/multi-track/) example looks like it has potential for some mixing board features to be added. I'm looking for an example to contribute to, so I would be happy to add some functionality here if it would be helpful.

Some possible additions for the individual tracks:

1. Volume faders
2. Solo buttons
3. Bypass buttons

<img width="737" alt="Screen Shot 2020-12-02 at 3 24 22 PM" src="https://user-images.githubusercontent.com/24415914/100927164-7d8abf00-34b2-11eb-902f-cf43d625ccf5.png">

The mobile-responsiveness aspect makes it somewhat tricky to fit everything though:

<img width="349" alt="Screen Shot 2020-12-02 at 3 34 06 PM" src="https://user-images.githubusercontent.com/24415914/100928854-c3e11d80-34b4-11eb-85e6-c88531318a32.png">

Perhaps it's best to keep it simple and start with just the volume faders and then add new issues for the additional features once this is complete? I can refer to the [Boombox example](https://mdn.github.io/webaudio-examples/audio-basics/) for how to implement the faders using the same styling, functionality and responsiveness settings. 

I think it makes sense to shrink the text and/or play button on page resize so the faders will all fit (mostly needed for the 'Lead Guitar' and 'Bass Guitar' tracks).

**Comment by chrisdavidmills** [comment]
Nice ideas here @matt-eric. I think I'd prefer that you submit these changes as a new version of the demo alongside the original (call it something like "multi-track-advanced") — that way we are not in danger of obfuscating what this demo is trying to illustrate, and we don't need to update the associated MDN tutorial to explain all the new code ;-)

**Comment by matt-eric** [comment]
Good plan @chrisdavidmills. I will make this into a new directory and leave the original as is.

**Comment by bsmth** [comment]
Thanks for reporting! I'm going to close this due to inactivity, but if you're still interested in tackling this, feel free to reply or open a PR with Chris' suggestions! Thank you :)
