### ISSUE TITLE
Visualization for OscillatorNode

### ISSUE THREAD

**Issue by VoloshchenkoAl** [mdn/webaudio-examples#46]
I have started to learn about [OscillatorNode](https://developer.mozilla.org/en-US/docs/Web/API/OscillatorNode), and find out that it is difficult to understand how the frequency and type of Oscillator affects a sound wave.

Is it a good idea to add visualization for OscillatorNode documentation? It will help to better understand how OscillatorNode works.

Example of visualization — https://codepen.io/VoloshchenkoAl/pen/gOwdpKx

**Comment by chrisdavidmills** [comment]
Issue moved to [mdn/content #1296](https://github.com/mdn/content/issues/1296) via [**ZenHub**](https://www.zenhub.com/)
