### ISSUE TITLE
media-source-buffer example doesn't work in Safari

### ISSUE THREAD

**Issue by nwang92** [mdn/webaudio-examples#55]
Live example: https://mdn.github.io/webaudio-examples/media-source-buffer/

I found this example from the docs here: https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/createMediaElementSource

With Safari (Version 15.2 build 17612.3.6.1.6), this example using `createMediaElementSource()` doesn't output any audio. It works fine in Chrome (96.0.4664.110) and Firefox (95.0.2).

**Comment by mart-jansink** [comment]
I just ran into the same problem. Luckily, a remark on a older WebKit issue related to `createMediaElementSource()` (https://bugs.webkit.org/show_bug.cgi?id=211394#c37) gave the solution: the `new AudioContext()` should be created after e.g. a `click` event since the `play` event apparently doesn't count as user input.

**Comment by nwang92** [comment]
I see, that makes sense. For others hitting this issue, here's some code I added to make it work.

First add a button:
```html
<body>
    <h1>createMediaElementSource example</h1>
    <button>Click me</button>
    ...
```

Then move the entirety of the existing `play` event handler into a `click` event handler of the button. Not super intuitive, but it does make the example work on Safari now:
```javascript
const button = document.querySelector('button');
button.addEventListener('click', event => {
  audioCtx = new AudioContext();
  // Create a MediaElementAudioSourceNode
  // Feed the HTMLMediaElement into it
  let source = audioCtx.createMediaElementSource(myAudio);

  // Create a gain node
  let gainNode = audioCtx.createGain();
  ...
```
