### ISSUE TITLE
Chrome: missing audioCtx.resume()

### ISSUE THREAD

**Issue by bbars** [mdn/webaudio-examples#8]
I've noticed problem here: https://mdn.github.io/webaudio-examples/audio-buffer/

When I click button, nothing happens (using Chrome). I see error message:
The AudioContext was not allowed to start. It must be resume (or created) after a user gesture on the page. https://goo.gl/7K7WLu.

I think, the click handler should start with `audioCtx.resume()` at https://github.com/mdn/webaudio-examples/blob/adabb2c83bf46aadaab586b37b197e3cb2264541/audio-buffer/index.html#L37-L39

**Comment by chrisdavidmills** [comment]
This seems to work for me; can you confirm this @bbars ?

Sorry for taking so long to respond.

**Comment by bbars** [comment]
Yes, it works as of Chrome 69. Maybe some playback policy was applied. Thank you!
