### ISSUE TITLE
The element has no supported sources.

### ISSUE THREAD

**Issue by Ce345** [mdn/webaudio-examples#94]
example of the example  of basics stops at line 109: audioElement.play();
Web Tools  of Chrome states: the element has no supported sources.
Something "basic" is missing. What could it be?

**Comment by Ce345** [comment]
Ai, correction:
Example named "audio-basics" stops at line 109: audioElement.play();
Web Tools of Chrome states: the element has no supported sources.
Something "basic" is missing. What could it be?

**Comment by teoli2003** [comment]
I just tried: https://mdn.github.io/webaudio-examples/audio-basics/ on Firefox and Chrome, and I don't get such an error. How do you try it?

**Comment by caugner** [comment]
Closing as stale (more info was requested, but not provided).
